### ISSUE TITLE
Optional dependencies

### ISSUE THREAD

**Issue by cliftonc** [tes/electrician#5]
The recent electric-metrics-gate highlighted the (potential) opportunity for optional dependencies.

```
dependsOn = ['config', 'db', {name: 'foo', optional: 'true'}]
```

Where if dependency 'foo' doesn't exist in the system it just injects a `null` in its place, where the component (given it defined it as optional) would need to deal with this appropriately.

For the specific example given we are just going to manually start the optional component within the other component, so 'hide' it behind its boundary.

/cc @andy-duncan @dmorgantini @bettiolo

**Comment by rouanw** [comment]
I don't see a need for this at Tes at the moment, so I'm going to close this for now.
